# Generated by Django 3.1.7 on 2023-04-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_recording', models.DateTimeField(auto_now_add=True)),
                ('reading_value', models.FloatField()),
                ('question_text', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
