# Generated by Django 3.1.7 on 2023-04-17 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='question_text',
            new_name='reading_details',
        ),
        migrations.AlterField(
            model_name='reading',
            name='time_of_recording',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 17, 17, 3, 6, 367491)),
        ),
    ]
