# Generated by Django 3.1.7 on 2023-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20230418_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_recording', models.DateTimeField()),
                ('reading_value', models.FloatField()),
                ('reading_details', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
